//
// Product types
export const FETCH_PRODUCT_REQUEST = "FETCH_PRODUCT_REQUEST"
export const FETCH_PRODUCT_SUCCESS = "FETCH_PRODUCT_SUCCESS"
export const FETCH_PRODUCT_FAILURE = "FETCH_PRODUCT_FAILURE"

//
// Cart types
export const FETCH_CART_DATA = "FETCH_CART_DATA"
export const FETCH_CART_LIST = "FETCH_CART_LIST"
